### ISSUE TITLE
Document new -XX:[+|-]MergeCompilerOptions

### ISSUE THREAD

**Issue by dsouzai** [eclipse-openj9/openj9-docs#1015]
**Issue or pull request number:**
https://github.com/eclipse-openj9/openj9/pull/16133

**Overview:**
By default, if multiple `-Xjit:` (with a colon) options are specified, only the last one is applied; if multiple `-Xaot:` (with a colon) options are specified, only the last one is applied. When `-XX:+MergeCompilerOptions` is specified, multiple `-Xjit:` (with a colon) options are merged into one, and multiple `-Xaot:` (with a colon) options are merged into one. If `-XX:-MergeCompilerOptions` is specified, then the merging does not happen (i.e., the default behaviour). 

**Release target:**
Eclipse OpenJ9 0.36.0

**Applies to the following JDK versions:**
All JDK versions

**Applies to the following platforms:**
All platforms

**New command line options:**

- Option name and syntax: `-XX:[+|-]MergeCompilerOptions`
- Purpose: To enable or disable merging multiple -Xjit options into one and multiple -Xaot options into one.

**Comment by Sreekala-Gopakumar** [comment]
I will take this up for 036.0 release.

**Comment by hzongaro** [comment]
One thing that wasn't immediately obvious to me in reading about this new option was what happens if several `-XX:[+|-]MergeCompilerOptions` were interleaved with several `-Xjit:` or `-Xaot:` options.  Would their processing be interleaved, resulting in merging of some compiler options, then overriding, then merging?

```
java -Xjit:version -XX:-MergeCompilerOptions -Xjit:verbose -XX:+MergeCompilerOptions -Xjit:vlog=vlog.txt CmdLineMerge
```

The answer is that the last setting for `MergeCompilerOptions` takes effect before the various `-Xjit:` and `-Xaot:` options are processed.  So in my example, `-XX:+MergeCompilerOptions` is in effect for all of the multiple `-Xjit:` options.

I just wanted to make sure that was clear for the documentation.
