### ISSUE TITLE
Add support for threadAllocatedBytes MXBean API

### ISSUE THREAD

**Issue by tajila** [eclipse-openj9/openj9-docs#1199]
**Issue or pull request number:**
https://github.com/eclipse-openj9/openj9/pull/18202

**Overview:**
Add support for getThreadAllocatedBytes com.sun.management.ThreadMXBean API. In previous releases it threw UnsupportedOperationException.
https://docs.oracle.com/javase/8/docs/jre/api/management/extension/com/sun/management/ThreadMXBean.html#getThreadAllocatedBytes-long-
https://docs.oracle.com/javase/8/docs/jre/api/management/extension/com/sun/management/ThreadMXBean.html#getThreadAllocatedBytes-long:A-
https://docs.oracle.com/en/java/javase/11/docs/api/jdk.management/com/sun/management/ThreadMXBean.html#getCurrentThreadAllocatedBytes()

**Release target:**
Eclipse OpenJ9 0.42.0

**Applies to the following JDK versions:**
JDK8+

**Applies to the following platforms:**
All platforms

**Comment by Sreekala-Gopakumar** [comment]
@tajila - Does the change in the milestones mean that in the Release 0.42.0, this change applies to only Java 21? This change will be applicable to all JDK versions only from Release 0.43.0 onwards? Thanks!

**Comment by pshipton** [comment]
The change is applicable to all versions. It is first available in 0.42, which only supports Java 21.

**Comment by pshipton** [comment]
We've backported the change to 0.41 now.

**Comment by Sreekala-Gopakumar** [comment]
> We've backported the change to 0.41 now.

@pshipton - Will this have an impact on 23_04 release of SDK 8, 11 and 17?

@sujathamibm - FYI

**Comment by pshipton** [comment]
> Will this have an impact on 23_04 release of SDK 8, 11 and 17?

No, it only affects OpenJ9 / Semeru.

**Comment by sujathamibm** [comment]
Sorry if I am repeating the question, Peter.
Just want to make sure that this change is not part of IBM Semeru Runtime Certified Edition, Version 11 and 17 on z/OS.

Regards,
Sujatha
________________________________
From: Peter Shipton ***@***.***>
Sent: Monday, November 13, 2023 6:40:08 PM
To: eclipse-openj9/openj9-docs ***@***.***>
Cc: Sujatha Mohan ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [eclipse-openj9/openj9-docs] Add support for threadAllocatedBytes MXBean API (Issue #1199)

Will this have an impact on 23_04 release of SDK 8, 11 and 17? No, it only affects OpenJ9 / Semeru. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned. Message ID: <eclipse-openj9/openj9-docs/issues/1199/1808137060@ github. com>
ZjQcmQRYFpfptBannerStart
This Message Is From an External Sender
This message came from outside your organization.
<https://us-phishalarm-ewt.proofpoint.com/EWT/v1/PjiDSg!2C-raNX0YrHwGY5T0iqOz0dqN0LI6h9G0vc765R9HMxI-Mcgx_6y_yydUneRezOuhrefjnb6cZm4w_TtcvKHempBwI9sjAHwKGJ1WjG-Cxcd_hVe8een$>
Report Suspicious

ZjQcmQRYFpfptBannerEnd

Will this have an impact on 23_04 release of SDK 8, 11 and 17?

No, it only affects OpenJ9 / Semeru.

**Comment by pshipton** [comment]
Correct, it's not part of this z/OS release, but will be in the next one.

Peter
________________________________
From: sujathamibm ***@***.***>
Sent: November 14, 2023 9:03 AM
To: eclipse-openj9/openj9-docs ***@***.***>
Cc: Peter Shipton ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [eclipse-openj9/openj9-docs] Add support for threadAllocatedBytes MXBean API (Issue #1199)

Sorry if I am repeating the question, Peter. Just want to make sure that this change is not part of IBM Semeru Runtime Certified Edition, Version 11 and 17 on z/OS. Regards, Sujatha ________________________________ From: Peter Shipton ***@ ***. ***>
ZjQcmQRYFpfptBannerStart
This Message Is From an External Sender
This message came from outside your organization.
<https://us-phishalarm-ewt.proofpoint.com/EWT/v1/PjiDSg!2C-raNX0YrHwGY5T0iqOz0dqN0LI6h9G0vc765R9HMxI-Mcgx_6y_yydUnewe1MO8IAgydaUbQYEZRWQTqdTzCNFIFnfvWlOsQjZkUDesXA0jk8bMkh3BTY$>
Report Suspicious

ZjQcmQRYFpfptBannerEnd

Sorry if I am repeating the question, Peter.
Just want to make sure that this change is not part of IBM Semeru Runtime Certified Edition, Version 11 and 17 on z/OS.

Regards,
Sujatha
________________________________
From: Peter Shipton ***@***.***>
Sent: Monday, November 13, 2023 6:40:08 PM
To: eclipse-openj9/openj9-docs ***@***.***>
Cc: Sujatha Mohan ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [eclipse-openj9/openj9-docs] Add support for threadAllocatedBytes MXBean API (Issue #1199)

Will this have an impact on 23_04 release of SDK 8, 11 and 17? No, it only affects OpenJ9 / Semeru. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned. Message ID: <eclipse-openj9/openj9-docs/issues/1199/1808137060@ github. com>
ZjQcmQRYFpfptBannerStart
This Message Is From an External Sender
This message came from outside your organization.
<https://us-phishalarm-ewt.proofpoint.com/EWT/v1/PjiDSg!2C-raNX0YrHwGY5T0iqOz0dqN0LI6h9G0vc765R9HMxI-Mcgx_6y_yydUneRezOuhrefjnb6cZm4w_TtcvKHempBwI9sjAHwKGJ1WjG-Cxcd_hVe8een$%3E
Report Suspicious

ZjQcmQRYFpfptBannerEnd

Will this have an impact on 23_04 release of SDK 8, 11 and 17?

No, it only affects OpenJ9 / Semeru.
