### ISSUE TITLE
AttachAPI updates control file access time for long-running applications every sleepDays specified via a system property com.ibm.tools.attach.fileAccessUpdateTime

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9-docs#1310]
**Issue or pull request number:**
* https://github.com/eclipse-openj9/openj9/issues/18720
* https://github.com/eclipse-openj9/openj9/pull/18996

**Overview:**
AttachAPI updates control file access time for long-running applications, added a system property `com.ibm.tools.attach.fileAccessUpdateTime` for `sleepDays` which has a default value `8` (days), a daemon thread is implemented to update AttachAPI control files every `sleepDays`. This prevents `Linux` `systemd` from deleting the aging files within /tmp after `10` days.
 If a `0` value is specified for the system property, the files won't be updated like previous behaviours.

**Release target:**
*Eclipse OpenJ9 0.44.0*

**Applies to the following JDK versions:**
*8 and later*

**Applies to the following platforms:**
*Linux X|P|Z*

**For new command line options:**

- Option name and syntax: *-Dcom.ibm.tools.attach.fileAccessUpdateTime=<8>*
- Default value: *8*
- Purpose: specify the interval days that AttachAPI updates control file access time for long-running applications.

**Comment by Sreekala-Gopakumar** [comment]
@JasonFengJ9 - Could you please check the following content and let me know if it is technically correct.

# -Dcom.ibm.tools.attach.fileAccessUpdateTime

**Linux&reg; on x86, Linux on IBM Power&reg; systems, and Linux on IBM Z&reg; systems (64-bit only)**

This option enables AttachAPI updates to the control file access time for long-running applications at specific intervals.

## Syntax

        -Dcom.ibm.tools.attach.fileAccessUpdateTime=<sleep days>

where `<sleep days>` is the number of interval days after which the AttachAPI updates the control file access time for long-running applications. The default value for `<sleep days>` is 8.

## Explanation

By default, the VM's AttachAPI places its notification files in the system temporary directory, `/tmp/.com_ibm_tools_attach`. Although the long-running AttachAPI uses the temporary notification files to operate, the VM does not open, modify, or read from these files after the files are created.

This causes a problem in Linux environments because by default `systemd-tmpfiles` automatically deletes all files and directories that are stored in `/tmp/` that have not been changed or read within a specific time period. By default, the files in `/tmp/` are cleaned up after 10 days.

You can specify the interval days that are less than or equal to 10 days (but greater that 0) after which the AttachAPI updates the control file access time with the `-Dcom.ibm.tools.attach.fileAccessUpdateTime` system property. This configuration prevents Linux `systemd` from deleting the files within `/tmp` after 10 days.

If `0` is specified as the number of `<sleep days>`, the control file access time is not updated and the files in `/tmp` are deleted after 10 days.

You can specify a different location to place the AttachAPI notification files with the [`-Dcom.ibm.tools.attach.directory`](dcomibmtoolsattachdirectory.md) system property, but AttachAPI with default settings will fail for VMs that run for longer than 10 days.

**Comment by Sreekala-Gopakumar** [comment]
@JasonFengJ9 @pshipton - Could you please check the content provided in https://github.com/eclipse-openj9/openj9-docs/issues/1310#issuecomment-2030079897. I would like to finalise this content as soon as possible. Thanks!

**Comment by pshipton** [comment]
It also applies to Aarch64 Linux, i.e. all Linux.

"By default, the files in the /tmp/ folder are cleaned up after 10 days." -> by `systemd`

Since you've mentioned the 10 day default here already, not sure it should continue to be mentioned in the following paragraph. The following can be removed
"that are less than or equal to 10 days"
"after 10 days" (2 occurrences)

"for longer than 10 days." -> "for longer than the `systemd` default for cleaning the `/tmp` directory."

**Comment by JasonFengJ9** [comment]
@Sreekala-Gopakumar please see my comments below, sorry for the late response.

> Although the long-running AttachAPI uses the temporary notification files to operate, the VM does not open, modify, or read from these files after the files are created.

The VM does not open, modify, or read from these files after the files are created if there is no attaching request.

> You can specify the interval days that are less than or equal to 10 days (but greater that 0) after which the AttachAPI updates the control file access time with the -Dcom.ibm.tools.attach.fileAccessUpdateTime system property. This configuration prevents Linux systemd from deleting the files within the /tmp folder after 10 days.

Any value can be specified to this system property. If there is a parsing `NumberFormatException`, the default `8` (days) is used, any value not greater than `0` will cause no update to the control files (same as previous behaviours before this change), a value greater than `10` is allowed though it only makes sense if the `systemd` has a greater cleanup interval.

> If 0 is specified as the number of <sleep days>, the control file access time is not updated and the files in the /tmp folder are deleted after 10 days.

The control files are deleted after 10 days only when `systemd` is enabled.

**Comment by Sreekala-Gopakumar** [comment]
> The VM does not open, modify, or read from these files after the files are created if there is no attaching request.

@JasonFengJ9 - What do you mean by "attaching request"? Also, can AttachAPI use the notification files if the VM does not access these files? Are these two things independent of each other?

**Comment by JasonFengJ9** [comment]
> What do you mean by "attaching request"?

It means an attaching VM attempts to attach a target VM, usually this involves locking control files (with write access), creating and reading files.

> Also, can AttachAPI use the notification files if the VM does not access these files? Are these two things independent of each other?

No, AttachAPI is a part of VM.

**Comment by Sreekala-Gopakumar** [comment]
@JasonFengJ9 @pshipton - I have updated the content. Please check https://github.com/eclipse-openj9/openj9-docs/issues/1310#issuecomment-2030079897. Thanks!

**Comment by pshipton** [comment]
> This option enables Attach API updates to the control file access time for long-running applications at specific intervals.

How about the following. There are multiple control files so I've added an `s` to "control file access time". The other places that use this should be made plural. 

This option enables Attach API updates at specific intervals to the control file access times, for long-running applications.

> and the files in the /tmp/ folder are deleted after 10 days if systemd is enabled.

after 10 days if systemd is enabled and has the default configuration.

> You can specify a different location to place the Attach API

a different location outside of the /tmp folder

**Comment by pshipton** [comment]
> the control file access time is not updated and the files in the /tmp/ folder are deleted after 10 days if systemd is enabled.

I suggest we make it generic.

the control file access times are not updated and the control files in the /tmp/ folder are deleted by systemd if it's enabled.

**Comment by Sreekala-Gopakumar** [comment]
@pshipton @JasonFengJ9 - Is there a difference between `systemd-tmpfiles` and `systemd`? If not, which term should we use?

> This causes a problem in Linux environments because by default `systemd-tmpfiles` automatically deletes all files and directories that are stored in the  `/tmp/` folder that have not been changed or read within a specific time period. By default, the files in the `/tmp/` folder are cleaned up after 10 days by `systemd`.

**Comment by pshipton** [comment]
In all cases here we are referring to `systemd-tmpfiles`. `systemd` is a shorter reference to `systemd-tmpfiles` or you could change them all to `systemd-tmpfiles`.
