### ISSUE TITLE
New CML option to ajust the extra number of startup hints that can be stored into the shared cache.

### ISSUE THREAD

**Issue by hangshao0** [eclipse-openj9/openj9-docs#1433]
**Issue or pull request number:**
https://github.com/eclipse-openj9/openj9/pull/20366

**Overview:**
Previously, there is no limit on the number of startup hints that can be stored into the shared cache. As long as the shared cache is not full/soft full, new startup hints can be stored. However, there could be applications that aggressively store a large number of startup hints that filled up the shared cache. No other data can be stored anymore. 

https://github.com/eclipse-openj9/openj9/pull/20366 introduces a limit on the additional number (which is 64 by default) of startup hints that can be stored into a shared cache. An command line utility option is added to adjust this number (see below).

User can use `-Xshareclasses:printStats=startuphint` or `-Xshareclasses:printDetails` to check how many startup hints are already stored and how many more can be stored in the shared cache. 

**Release target:**
Eclipse OpenJ9 0.49.0

**Applies to the following JDK versions:**
All versions

**Applies to the following platforms:**
All platforms

**For new command line options:**

- Option name and syntax: `-Xshareclasses:extraStartupHints=<number>`
- If values are set:
	`<number>` should be an integer >=0.
- Purpose: 
        By default, a shared cache allows at most 64 startup hints to be stored. This count is decremented by 1 after 1 startup hints is stored. No more hints can be stored once it reaches 0. User can use `-Xshareclasses:extraStartupHints=<number>` to adjust this count as needed. e.g.  `-Xshareclasses:extraStartupHints=0` prevents any new hints to be stored. `-Xshareclasses:extraStartupHints=10` allows 10 more new hints to be stored.
- Restrictions: N.A.

**Comment by Sreekala-Gopakumar** [comment]
@hangshao0 - In the [-Xshareclasses](https://eclipse.dev/openj9/docs/xshareclasses/) topic, the `printDetails` parameter is not discussed. Since you have mentioned this parameter ("User can use -Xshareclasses:printStats=startuphint or -Xshareclasses:printDetails to check how many startup hints are already stored and how many more can be stored in the shared cache."), shouldn't we discuss this parameter in this topic?
If yes, could you please share some content related to this parameter?

Thanks!
