### ISSUE TITLE
JITServer -XX options need to be documented

### ISSUE THREAD

**Issue by dmitry-ten** [eclipse-openj9/openj9-docs#816]
JITServer added a bunch of `-XX` options, such as `+UseJITServer`, `+RequireJITServer`, `JITServerAddress=`, etc.

We need to document each option in preparation for the JITServer GA.

**Comment by dmitry-ten** [comment]
I'll make a pull request once I write the required documentation.
@mpirvu fyi.

**Comment by doveye** [comment]
@dmitry-ten Can you please provide more information. There is a [template](https://github.com/eclipse-openj9/openj9-docs/issues/new?assignees=&labels=&template=new-documentation-change.md) to help when creating issues. For example:

- What's the related code issue?
- Which release is this targeted at? (0.28?)
- Which JDK versions does this apply to? (Currently, the docs say JDK 8 and 11 but 0.28 supports JDK 17 so will JITServer be available on that version too?)
- Which platforms does this apply to? (There is already a list in the docs, are there any changes to that list?)

You mentioned GA - presumably you mean that JITServer will go from a tech preview to a fully-fledged feature? Is that due to happen for 0.28? 

- If yes, then we can go ahead with the separate topics for the -XX options but we'll need to remove "(tech preview)" from the mdkocs.yml file and the title of the jitserver.md topic, and rewrite that topic to move more of the content to the -XX topics. I can probably help with that.
- If no, then we shouldn't create separate topics for the -XX options - any that aren't already mentioned in the jitserver.md topic should be added there, to keep all the tech preview content separate from the rest of the docs.

Changes for 0.28 should be summarized for users in the what's new topic: https://eclipse-openj9.github.io/openj9-docs/version0.28/ (you can see an example at https://eclipse-openj9.github.io/openj9-docs/version0.23/#extended-platform-support-for-the-jitserver-technology-preview).

**Comment by mpirvu** [comment]
**Issue or pull request number:**
There are several PRs that are related to this documentation, most of them quite old.
A couple of the recent ones: https://github.com/eclipse-openj9/openj9/pull/13303 https://github.com/eclipse-openj9/openj9/pull/13288 

**Overview:**
*JITServer tech has a few `-XX:` options that can be used for user tuning. These options need to be properly documented much like the other XX options.*

**Release target:**
*Eclipse OpenJ9 0.28.0*

**Applies to the following JDK versions:**
*All JDK versions, including JDK17. Note that we say that JITServer is supported only on the LTS JDKs, i.e 8,11,17, but the options should work on any JDK version*

**Applies to the following platforms:**
*Linux X|P|Z*

> You mentioned GA - presumably you mean that JITServer will go from a tech preview to a fully-fledged feature? Is that due to happen for 0.28?

Indeed, the plan is to move from tech-preview to a supported feature starting with release 0.28, but only for Linux on X/P. Linux on Z will remain "tech preview" until the next release.

**Comment by doveye** [comment]
Thanks for the extra info. We might also want to announce the change of tech preview to fully-supported feature in the release notes at https://github.com/eclipse-openj9/openj9/blob/master/doc/release-notes/0.28/0.28.md? (Depends whether it's a "notable change".)

**Comment by doveye** [comment]
Reopening as although one PR has been merged, further updates are required, which I will have a look at.

**Comment by doveye** [comment]
The other PR was merged, so closing this issue.
